all: assignment1 assignment2

assignment1: sales.c
	gcc sales.c -o assignment1

#assignment2: temperature_converter.c
#	gcc temperature_converter.c -o assignment2
clean:
#	rm -rf assignment1 assignment2